name: Deploy to ConoHa WING

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to ConoHa via SSH
      uses: easingthemes/ssh-deploy@v5.0.3
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USER }}
        REMOTE_PORT: ${{ secrets.SSH_PORT }}
        SOURCE: "./"
        TARGET: "/home/${{ secrets.SSH_USER }}/public_html/portfolio.tnbkn.com/"
        EXCLUDE: "/dist/, /node_modules/, /.git/, /.github/, /README.md, /.DS_Store"